apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticstack-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mlliarm/eck-gitops-infra.git' # Use your real GitHub repository URL here
    targetRevision: HEAD
    path: 'apps/elasticsearch'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
